### ISSUE TITLE
Testing S2S ODAS

### ISSUE THREAD

**Issue by ehackert** [GEOS-ESM/GEOSgcm#25]
Tom asked me to test out the GITHUB version of the ODAS code.   So far I set up a run where I pulled the GITHUB versions to the directory structure that the old CVS version followed.   This experiment is located in 
```script
/gpfsm/dnb42/projects/p17/ehackert/geos5/exp/eh018/*. 
```  
For the 1st pass through, I reused the model (GEOSgcm.x) from the CVS version.   The error file is located in 

```script
 /gpfsm/dnb42/projects/p17/ehackert/geos5/exp/eh018/oldruns/eh018.e33633168
```
More recently I copied the GEOSgcm.x from the GITHUB version and reran.   These results are located in  
```scritp
/gpfsm/dnb42/projects/p17/ehackert/geos5/exp/eh018/eh018.e33638608
```
Tom suggested that I change out the g5_modules in the shell so I will run this test to see if some (or all) of the errors are gone.   I'll let you know the outcome. 

Thanks.

eric

**Comment by tclune** [comment]
I've edited the original ticket to  fix a typo in the paths and make the output references a bit easier to read.    Here I'll include snippets of the actual error messages.    

The first error log shows
```script
mpirun -np $NP $UMD_LETKFUTILS/ocean_sponge.py $yyyy $mm $dd > ocean_sponge.out
rm temp_salt_sponge.nc
rm: cannot remove `temp_salt_sponge.nc': No such file or directory
$UMD_LETKFUTILS/ocean_iau.x -DO_SPONGE ${ODAS_dt_restore_sst}
/gpfsm/dnb42/projects/p17/ehackert/geos5/exp/eh018/ocean_das/UMD_Etc/UMD_utils/\
/ocean_iau.x: symbol lookup error: /gpfsm/dnb42/projects/p17/ehackert/geos5/exp\
/eh018/ocean_das/UMD_Etc/UMD_utils//ocean_iau.x: undefined symbol: mpi_sgi_inpl\
ace
cp temp_salt_sponge.nc $SCRDIR/INPUT/
cp: cannot stat `temp_salt_sponge.nc': No such file or directory
ln -s temp_salt_sponge.nc $SCRDIR/INPUT/temp_sponge_coeff.nc
ln -s temp_salt_sponge.nc $SCRDIR/INPUT/temp_sponge.nc
```

Further in on the 2nd output this type of error shows up:
```script
@ NPES = $NX * $NY
$RUN_CMD $NPES ./GEOSgcm.x | tee geos.out
./GEOSgcm.x: error while loading shared libraries: libmpi++abi1002.so: cannot o\
pen shared object file: No such file or directory
./GEOSgcm.x: error while loading shared libraries: libmpi++abi1002.so: cannot o\
pen shared object file: No such file or directory
```

**Comment by mathomp4** [comment]
First things first, yes, I believe some/all of this is related to `g5_modules`. The first experiment you pointed me to was built with Intel MPI according to this:
```
/gpfsm/dnb42/projects/p17/ehackert/geos5/sandbox_try4/GEOSodas/src/g5_modules
```
You definitely can't use an Intel MPI `g5_modules` with MPT executables and vice-versa.

Second, you'll want to look over your scripts for references to `mpirun`. With MPT, `mpirun` does Very Weird Things™. The easiest solution is to use `esma_mpirun` from the installation binary directory as it tries to auto-detect your MPI stack and use the right command. This is how things are done now, but your jobs seem to be from Heracles(?) days. At that point we hadn't quite gotten as general. You might have (in `gcm_run.j`):
```tcsh
setenv RUN_CMD "mpirun -np"
```
Now we do:
```tcsh
setenv RUN_CMD "$GEOSBIN/esma_mpirun -np"
```
In your testing, if your code was compiled with MPT, you'd at least need to use:
```tcsh
setenv RUN_CMD "mpiexec_mpt -np"
```

I do see one other possible excitement:
```
 mpirun -np $NP $UMD_LETKFUTILS/ocean_sponge.py $yyyy $mm $dd > ocean_sponge.out
```
Are you using `mpi4py`? Because support for that is tricky.

**Comment by ehackert** [comment]
Hi Matt,
Thanks for taking a look at this.   I made your suggested corrections, fixing all instances of the old g5_modules.  In addition I put in the suggested mpi run correction as well for all scripts.   I am submitting this now.   Thanks.

eric

**Comment by ehackert** [comment]
Hi Matt,

I tried replacing all instances of g5_modules with the Git version.   In addition, I replaced all the mpi commands with your suggestions.   Finally, I replaced the read_merra2_bcs.so with the Git version since it looked like it was choking there.   Now the code is complaining about a plotting call in ocean_sponge.py (see eh018.e 33728536 for details).  Also the model is bombing immediately.    Any help you can suggest would be appreciated.    Thanks.

Eric

**Comment by mathomp4** [comment]
@ehackert 

Looking at `/gpfsm/dnb42/projects/p17/ehackert/geos5/exp/eh018/eh018.o33728536` my guess is that it's because what ever `CAP.rc.tmpl` or the like you are using still has GCS as the root:
```
MAPLROOT_COMPNAME: GCS
        ROOT_NAME: GCS
```
This was changed when we moved to Github to be `GCM`:
```
MAPLROOT_COMPNAME: GCM
        ROOT_NAME: GCM
```
Try making that change and things might go farther.
