### ISSUE TITLE
Disabling both GOCART and TR crashes model

### ISSUE THREAD

**Issue by AgilentGCMS** [GEOS-ESM/GEOSgcm#260]
I am running the GCM (branch `10.17.0`) with SF6 through TR gridcomp successfully, with replay enabled. The run directory is at `/discover/nobackup/projects/gmao/geos_carb/sbasu1/runs/GCM/Jason_10.17.0_sf6_mip_c180`. I needed to run the same circulation but without any tracers, i.e., without TR. I followed the following steps:

1. I cloned that with `/discover/nobackup/sbasu1/GEOS/source/GEOSgcm-v10.17.0/install/bin/gcm_setup`. I selected ‘Yes’ to if I want to clone an experiment, then provided the source folder as above, and the new experiment tag `Jason_10.17.0_mass_fluxes`.
2. Once cloned, I copied over `*_internal_rst` and `cap_restart` from the folder `Jason_10.17.0_sf6_mip_c180` (the source of the clone) to `Jason_10.17.0_mass_fluxes` (the new run folder). That meant I was starting from restarts written out by the same model version.
3. I changed the end date in `CAP.rc` to 1 day after `cap_restart`, just to test.
4. In `RC/Chem_Registry.rc`, I set `doing_TR:  no`, and in `RC/GEOS_ChemGridComp.rc` I set `ENABLE_TR:  .FALSE.` to disable TR in this new run. In addition, in `HISTORY.rc` I made sure `COLLECTIONS` was empty.
5. I submitted the job with `sbatch -t 60 --qos debug gcm_run.j`

I was hoping this would run the model for 1 day without TR. However, the model triggered an error in `MAPL_Generic.F90` that makes no sense to me. The full log can be found at `/discover/nobackup/projects/gmao/geos_carb/sbasu1/runs/GCM/Jason_10.17.0_mass_fluxes/slurm-42861658.out`

Ben Auer tried replicating this at his end, and his model crashed with a different error. I'll let him fill in those details. Seems like a corner case that happens when neither GOCART nor TR are running.

**Comment by bena-nasa** [comment]
It might be ok, if AddConnectivity's import doesn't exist. In that case, perhaps there is shot of figuring this out. Checking on this now.

**Comment by AgilentGCMS** [comment]
Hmm... I admit I've not tried running without GOCART **and** TR before. I'll try this with an earlier model version to see if that works, out of curiosity.

**Comment by bena-nasa** [comment]
I was able to turn both of these off in v10.17.3 if I did the following in the AGCM.rc
```
USE_AEROSOL_NN: 0
SYNCTQ: 0
```
SYNCTQ 0 turns off the TerminateImport that was causing problems. I also had to disable the aerosol callback in moist explicit with the USE_AEROSOL_NN, otherwise I got a divide by zero error there. 

This is what seems to work in the latest Git tag.

**Comment by AgilentGCMS** [comment]
I can confirm that those two settings in `AGCM.rc` work, i.e., the model runs without crashing. However, if I run a single species in TR, namely SF6, that isn't providing any aerosols, correct? Then why does running TR with just SF6 **not** require `USE_AEROSOL_NN: 0`?

**Comment by bena-nasa** [comment]
Because the aerosols use for this callback from moist and radiation are the aerosols produced by the component specified with AERO_PROVIDER which is NONE or GOCART or GOCART.data, this callback mechanism does not call back to TR.  
I would not say TR has anything to do with aerosols. It's constituents are ultimately packed into the same tracer bundle as the aerosols produced by gocart so they can be shipped to the dynamics for advection but otherwise are unrelated.
