### ISSUE TITLE
make_bcs and make_tile do not work

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOSgcm#42]
The make_tile and make_bcs scripts are not working in the new CMake build system. User bena-nasa has gotten a first stab at cmake so that Raster/src will build and install as part of the install target (although I have not tried to match the old flags or build the 2 libraries, will need help from Tom and Matt with this). However, the make_bcs and make_tile script are just broken, they were building the src directory and then using another makefile as a scripting language and running in source. These need to be completely rewritten to reference the executables in the install directory, run anywhere, etc...

**Comment by JustinPerket** [comment]
@smahanam would you be willing to sit down together to get make_bcs and make_tile functional and validated with the cvs version? Heavier rewrites, and future plans of these tools can be discussed as a bigger group

**Comment by tclune** [comment]
@smahanam  I do not get the association of OpenMP with the issue that Ben mentioned.    His concern is the code is making assumptions about the directory location (src) and the underlying build mechanism.

Turning on OpenMP for an executable is straightforward for any given executable.   But it should work (albeit more slowly) without activating OpenMP.

**Comment by smahanam** [comment]
I am able to build the Raster/ directory now. I will modify make_bcs to create BCs for all resolutions 
 and Atmos-Ocean combinations that it currently supports.
@tclune if you could point me to a CMake file example that uses OpenMP, I can make that change and try - Thanks !

**Comment by JustinPerket** [comment]
@smahanam Any progress on making make_bcs and make_tile functional (with or without OpenMP)?

**Comment by smahanam** [comment]
Thanks for the reminder. I just started working on it yesterday. We removed "src" in "Shared/Raster" and moved all codes from src to Shared/Raster.
That would be my next PR along with some fix to start with for [#46](https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/46)

**Comment by JustinPerket** [comment]
I would argue this is more crucial. We can't release a stable LDAS tag without these working

**Comment by smahanam** [comment]
It shouldn't take long (maybe, next week). I was cleaning my own backlog of CVS to git transition.
I don't know why you hold the LDAS stable tag for make_bcs modifications, though. The LDAS tag has nothing to with make_bcs. We have produced Icarus-NLv3 and we will use it. 

The next time we will use make_bcs when we plan to produce the next version of BCs that is some months away. 
We only have one modification to BCs since NLv3, which I am sure Rolf looks forward to have (use peatland parameters in the below paper).

 Bechtold, M., De Lannoy, G. J. M., Koster, R. D., Reichle, R. H., Mahanama, S. P., Bleuten, W., et al. ( 2019). PEAT‐CLSM: A specific treatment of peatland hydrology in the NASA Catchment Land Surface Model. Journal of Advances in Modeling Earth Systems, 11, 2130– 2162. https://doi.org/10.1029/2018MS001574

**Comment by JustinPerket** [comment]
make_bcs is part of the GEOSgcm_GridComp repository (maybe this issue should be moved/referenced there), so LDAS has it too. I would argue we should not have a stable release of the GCM or LDAS with these utilities broken.

**Comment by JustinPerket** [comment]
Update:
@smahanam has a fix for make_bcs in the [GEOSgcm_GC branch bugfix/make_bcs_update](https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/bugfix/make_bcs_update), undergoing some tests.

**Comment by mathomp4** [comment]
I'm going to close this. I believe it works now and if not, a new ticket can be opened.
